import React, { useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Clock, Dumbbell, Pencil, Plus, Trash2, X } from "lucide-react";
import { apiRequest } from "../services/api.js";
import { calendarDays, localDateKey, monthRange } from "../utils/agenda.js";

const WEEKDAYS = ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"];

const monthTitle = date => new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric", timeZone: "America/Sao_Paulo" }).format(date);
function dateLabel(key) { const [year, month, day] = key.split("-").map(Number); return new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "2-digit", month: "long", timeZone: "America/Sao_Paulo" }).format(new Date(year, month - 1, day)); }
const emptyForm = (date = localDateKey(new Date())) => ({ title: "", event_date: date, event_time: "09:00", student_id: "", notes: "", visible_to_student: false });

export default function AgendaModule({ role = "personal", students = [] }) {
  const studentView = role === "student";
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selectedDate, setSelectedDate] = useState(() => localDateKey(new Date()));
  const [items, setItems] = useState([]); const [status, setStatus] = useState("loading"); const [error, setError] = useState("");
  const [filter, setFilter] = useState("all"); const [dialog, setDialog] = useState(null); const [form, setForm] = useState(() => emptyForm());
  const [saving, setSaving] = useState(false); const [confirmDelete, setConfirmDelete] = useState(null); const closeRef = useRef(null);
  const range = useMemo(() => monthRange(month), [month]); const days = useMemo(() => calendarDays(month), [month]);

  const load = async () => { setStatus("loading"); setError(""); try { const response = await apiRequest(`/agenda?start=${range.start}&end=${range.end}`); setItems(Array.isArray(response?.items) ? response.items : []); setStatus("success"); } catch (requestError) { setError(requestError?.message || "Não foi possível carregar a agenda."); setStatus("error"); } };
  useEffect(() => { load(); }, [range.start, range.end]);
  useEffect(() => { if (dialog) closeRef.current?.focus(); }, [dialog]);

  const filtered = useMemo(() => items.filter(item => filter === "all" || item.kind === filter), [filter, items]);
  const selectedItems = filtered.filter(item => item.event_date === selectedDate);
  const upcoming = filtered.filter(item => item.event_date >= localDateKey(new Date())).slice(0, 8);
  const itemsByDate = useMemo(() => filtered.reduce((result, item) => { (result[item.event_date] ||= []).push(item); return result; }, {}), [filtered]);
  const moveMonth = amount => setMonth(current => new Date(current.getFullYear(), current.getMonth() + amount, 1));
  const goToday = () => { const today = new Date(); setMonth(new Date(today.getFullYear(), today.getMonth(), 1)); setSelectedDate(localDateKey(today)); };
  const openCreate = () => { setForm(emptyForm(selectedDate)); setDialog({ mode: "form", item: null }); };
  const openEdit = item => { setForm({ title: item.title, event_date: item.event_date, event_time: String(item.event_time || "09:00").slice(0, 5), student_id: item.student_id || "", notes: item.notes || "", visible_to_student: Boolean(item.visible_to_student) }); setDialog({ mode: "form", item }); };
  const submit = async event => { event.preventDefault(); if (saving) return; setSaving(true); setError(""); const payload = { ...form, student_id: form.student_id || null, notes: form.notes.trim() || null }; try { await apiRequest(dialog.item ? `/agenda/events/${dialog.item.id}` : "/agenda/events", { method: dialog.item ? "PATCH" : "POST", body: JSON.stringify(payload) }); setDialog(null); await load(); } catch (requestError) { setError(requestError?.message || "Não foi possível salvar o compromisso."); } finally { setSaving(false); } };
  const remove = async () => { if (!confirmDelete || saving) return; setSaving(true); try { await apiRequest(`/agenda/events/${confirmDelete.id}`, { method: "DELETE" }); setConfirmDelete(null); setDialog(null); await load(); } catch (requestError) { setError(requestError?.message || "Não foi possível excluir o compromisso."); } finally { setSaving(false); } };

  return <section className="agenda-v2-page">
    <header className="agenda-v2-header"><div><p className="eyebrow">Rotina organizada</p><h2>Agenda</h2><p>{studentView ? "Seus treinos e compromissos compartilhados." : "Treinos programados e compromissos em um só lugar."}</p></div>{!studentView && <button className="metal-button agenda-new" type="button" onClick={openCreate}><Plus size={18}/> Novo compromisso</button>}</header>
    <div className="agenda-v2-toolbar"><div className="agenda-month-nav"><button type="button" aria-label="Mês anterior" onClick={() => moveMonth(-1)}><ChevronLeft/></button><strong>{monthTitle(month)}</strong><button type="button" aria-label="Próximo mês" onClick={() => moveMonth(1)}><ChevronRight/></button><button type="button" onClick={goToday}>Hoje</button></div><div className="agenda-filters" role="group" aria-label="Filtrar agenda">{[["all","Todos"],["workout","Treinos"],["appointment","Compromissos"]].map(([value,label])=><button type="button" key={value} className={filter===value?"active":""} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div></div>
    {status === "loading" && <div className="tenant-data-state" role="status"><strong>Carregando agenda...</strong><span>Buscando eventos do mês visível.</span></div>}
    {status === "error" && <div className="tenant-data-state error" role="alert"><strong>Não foi possível carregar a agenda</strong><span>{error}</span><button type="button" onClick={load}>Tentar novamente</button></div>}
    {status === "success" && <div className="agenda-v2-layout">
      <article className="agenda-month-card" aria-label={`Calendário de ${monthTitle(month)}`}><div className="agenda-weekdays">{WEEKDAYS.map(day=><span key={day}>{day}</span>)}</div><div className="agenda-month-grid">{days.map(day=>{const dateItems=itemsByDate[day.key]||[];return <button type="button" key={day.key} className={`${day.currentMonth?"":"outside"} ${selectedDate===day.key?"selected":""}`} onClick={()=>setSelectedDate(day.key)} aria-label={`${dateLabel(day.key)}, ${dateItems.length} evento(s)`}><span>{day.day}</span><div>{dateItems.slice(0,3).map(item=><i key={item.id} className={item.kind} title={item.title}>{item.kind==="workout"?<Dumbbell size={12}/>:<Clock size={12}/>}<em>{item.title}</em></i>)}{dateItems.length>3&&<small>+{dateItems.length-3}</small>}</div></button>})}</div></article>
      <aside className="agenda-day-panel"><p className="eyebrow">Dia selecionado</p><h3>{dateLabel(selectedDate)}</h3>{selectedItems.length?<ul>{selectedItems.map(item=><li key={item.id}><button type="button" onClick={()=>setDialog({mode:"detail",item})}><span className={`agenda-kind ${item.kind}`}>{item.kind==="workout"?<Dumbbell/>:<CalendarDays/>}</span><div><strong>{item.title}</strong><small>{item.event_time?String(item.event_time).slice(0,5):"Horário livre"}{item.student_name?` • ${item.student_name}`:""}</small></div></button></li>)}</ul>:<div className="agenda-empty"><CalendarDays/><strong>Nenhum compromisso neste dia.</strong><span>{studentView?"Quando houver algo relacionado a você, aparecerá aqui.":"Selecione outro dia ou crie um compromisso."}</span></div>}</aside>
      <section className="agenda-upcoming"><h3>Próximos eventos</h3>{upcoming.length?<ul>{upcoming.map(item=><li key={item.id}><button type="button" onClick={()=>{setSelectedDate(item.event_date);setDialog({mode:"detail",item});}}><time>{item.event_date.split("-").reverse().slice(0,2).join("/")}<small>{item.event_time?String(item.event_time).slice(0,5):"Treino"}</small></time><span><strong>{item.title}</strong><small>{item.student_name|| (item.kind==="workout"?"Treino programado":"Compromisso")}</small></span></button></li>)}</ul>:<p>Nenhum próximo evento neste período.</p>}</section>
    </div>}
    {dialog && <div className="agenda-dialog-backdrop" role="presentation" onMouseDown={()=>setDialog(null)}><section className="agenda-dialog" role="dialog" aria-modal="true" aria-labelledby="agenda-dialog-title" onMouseDown={event=>event.stopPropagation()}><button ref={closeRef} className="agenda-dialog-close" type="button" aria-label="Fechar" onClick={()=>setDialog(null)}><X/></button>{dialog.mode==="detail"?<><p className="eyebrow">{dialog.item.kind==="workout"?"Treino programado":"Compromisso"}</p><h3 id="agenda-dialog-title">{dialog.item.title}</h3><dl><div><dt>Data</dt><dd>{dateLabel(dialog.item.event_date)}</dd></div><div><dt>Horário</dt><dd>{dialog.item.event_time?String(dialog.item.event_time).slice(0,5):"Não definido"}</dd></div>{dialog.item.student_name&&<div><dt>Aluno</dt><dd>{dialog.item.student_name}</dd></div>}<div><dt>Status</dt><dd>{dialog.item.status}</dd></div></dl>{dialog.item.notes&&<p>{dialog.item.notes}</p>}{!studentView&&dialog.item.editable&&<div className="agenda-dialog-actions"><button type="button" onClick={()=>openEdit(dialog.item)}><Pencil/> Editar</button><button className="danger" type="button" onClick={()=>setConfirmDelete(dialog.item)}><Trash2/> Excluir</button></div>}</>:<form onSubmit={submit}><p className="eyebrow">Agenda</p><h3 id="agenda-dialog-title">{dialog.item?"Editar compromisso":"Novo compromisso"}</h3><label>Título *<input required minLength="2" maxLength="160" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="agenda-form-row"><label>Data *<input required type="date" value={form.event_date} onChange={e=>setForm({...form,event_date:e.target.value})}/></label><label>Horário *<input required type="time" value={form.event_time} onChange={e=>setForm({...form,event_time:e.target.value})}/></label></div><label>Aluno<select value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">Sem aluno</option>{students.map(student=><option key={student.id} value={student.id}>{student.name}</option>)}</select></label><label>Observações<textarea maxLength="2000" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="agenda-checkbox"><input type="checkbox" checked={form.visible_to_student} disabled={!form.student_id} onChange={e=>setForm({...form,visible_to_student:e.target.checked})}/> Visível para o aluno selecionado</label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="metal-button" type="submit" disabled={saving}>{saving?"Salvando...":"Salvar compromisso"}</button></form>}</section></div>}
    {confirmDelete&&<div className="agenda-dialog-backdrop" role="presentation"><section className="agenda-dialog agenda-confirm" role="alertdialog" aria-modal="true" aria-labelledby="delete-agenda-title"><Trash2/><h3 id="delete-agenda-title">Excluir compromisso?</h3><p>Esta ação remove somente o compromisso. Aluno, treino e histórico serão preservados.</p><div className="agenda-dialog-actions"><button type="button" onClick={()=>setConfirmDelete(null)}>Cancelar</button><button className="danger" type="button" disabled={saving} onClick={remove}>{saving?"Excluindo...":"Excluir"}</button></div></section></div>}
  </section>;
}
