import React, { useEffect, useMemo, useState } from "react";
import { Download, Eye, EyeOff, FileText, LoaderCircle, Pencil, Trash2, Upload } from "lucide-react";
import { apiDownload, apiRequest } from "../services/api.js";

const categories = [["document", "Documento"], ["assessment", "Avaliação"], ["workout", "Treino"], ["nutrition", "Nutrição"], ["other", "Outro"]];
const formatSize = (value) => value >= 1024 * 1024 ? `${(value / 1024 / 1024).toFixed(1)} MB` : `${Math.ceil(value / 1024)} KB`;
const formatDate = (value) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(value));
const allowedTypes = new Set(["application/pdf", "image/jpeg", "image/png", "image/webp"]);
function saveBlob(blob, filename) { const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = filename; anchor.click(); URL.revokeObjectURL(href); }

export default function PersonalFiles({ students = [] }) {
  const [studentId, setStudentId] = useState(students[0]?.id || ""); const [files, setFiles] = useState([]); const [status, setStatus] = useState("idle"); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false);
  const selectedStudent = useMemo(() => students.find((item) => String(item.id) === String(studentId)), [students, studentId]);
  const load = async () => { if (!studentId) { setFiles([]); setStatus("ready"); return; } setStatus("loading"); setMessage(""); try { setFiles(await apiRequest(`/files?student_id=${encodeURIComponent(studentId)}`)); setStatus("ready"); } catch (error) { setMessage(error.message); setStatus("error"); } };
  useEffect(() => { load(); }, [studentId]); // eslint-disable-line react-hooks/exhaustive-deps
  const upload = async (event) => { event.preventDefault(); const form = event.currentTarget; const chosen = form.elements.file.files?.[0]; if (!chosen || !studentId) return; if (!allowedTypes.has(chosen.type)) { setMessage("Envie um arquivo PDF, JPG, PNG ou WebP."); return; } if (chosen.size > 10 * 1024 * 1024) { setMessage("O arquivo deve ter no máximo 10 MB."); return; } const body = new FormData(); body.append("student_id", studentId); body.append("file", chosen); body.append("title", form.elements.title.value); body.append("description", form.elements.description.value); body.append("category", form.elements.category.value); body.append("visible_to_student", String(form.elements.visible_to_student.checked)); setUploading(true); setMessage(""); try { await apiRequest("/files", { method: "POST", body, timeoutMs: 30000 }); form.reset(); setMessage("Arquivo enviado com segurança."); await load(); } catch (error) { setMessage(error.message); } finally { setUploading(false); } };
  const toggleVisibility = async (file) => { setMessage(""); try { await apiRequest(`/files/${file.id}`, { method: "PATCH", body: JSON.stringify({ visible_to_student: !file.visible_to_student }) }); await load(); } catch (error) { setMessage(error.message); } };
  const editTitle = async (file) => { const title = window.prompt("Título do arquivo", file.title || ""); if (title === null) return; try { await apiRequest(`/files/${file.id}`, { method: "PATCH", body: JSON.stringify({ title }) }); await load(); } catch (error) { setMessage(error.message); } };
  const remove = async (file) => { if (!window.confirm(`Excluir ${file.title || file.original_filename}?`)) return; try { await apiRequest(`/files/${file.id}`, { method: "DELETE" }); await load(); } catch (error) { setMessage(error.message); } };
  const download = async (file) => { try { const result = await apiDownload(`/files/${file.id}/download`); saveBlob(result.blob, result.filename || file.original_filename); } catch (error) { setMessage(error.message); } };
  return <section className="private-files-page">
    <header className="private-files-heading"><div><p className="eyebrow">Armazenamento privado</p><h2>Arquivos dos alunos</h2><p>Envie documentos e escolha explicitamente o que cada aluno pode visualizar.</p></div><label>Aluno<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">Selecione</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label></header>
    {message && <p className="private-files-message" role="status">{message}</p>}
    {selectedStudent && <form className="private-files-upload" onSubmit={upload}><label>Arquivo<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required /></label><label>Título<input name="title" maxLength="180" placeholder="Título opcional" /></label><label>Categoria<select name="category">{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="wide">Descrição<textarea name="description" maxLength="2000" rows="2" /></label><label className="private-file-checkbox"><input name="visible_to_student" type="checkbox" /> Visível para o aluno</label><button className="primary-action" type="submit" disabled={uploading}>{uploading ? <LoaderCircle className="spin" size={18} /> : <Upload size={18} />} Enviar</button><small className="wide">PDF, JPG, PNG ou WebP. Máximo de 10 MB.</small></form>}
    {status === "loading" ? <div className="private-files-state"><LoaderCircle className="spin" /> Carregando...</div> : files.length === 0 ? <div className="private-files-empty"><FileText size={28} /><strong>Nenhum arquivo para este aluno</strong><span>Os arquivos enviados aparecerão aqui.</span></div> : <div className="private-files-grid">{files.map((file) => <article className="private-file-card" key={file.id}><div className="private-file-icon"><FileText /></div><div className="private-file-copy"><strong>{file.title || file.original_filename}</strong><span>{file.original_filename} · {formatSize(file.size_bytes)} · {formatDate(file.created_at)}</span><em>{file.visible_to_student ? "Visível para o aluno" : "Privado do Personal"}</em></div><div className="private-file-actions"><button className="icon-action" type="button" title="Editar título" onClick={() => editTitle(file)}><Pencil size={19} /></button><button className="icon-action" type="button" title={file.visible_to_student ? "Ocultar do aluno" : "Liberar para o aluno"} onClick={() => toggleVisibility(file)}>{file.visible_to_student ? <EyeOff size={19} /> : <Eye size={19} />}</button><button className="icon-action" type="button" title="Baixar" onClick={() => download(file)}><Download size={19} /></button><button className="icon-action danger" type="button" title="Excluir" onClick={() => remove(file)}><Trash2 size={19} /></button></div></article>)}</div>}
  </section>;
}
