import React, { useEffect, useMemo, useState } from "react";
import { Ban, CircleDollarSign, Plus, Receipt, Wallet, X } from "lucide-react";
import { apiRequest } from "../services/api.js";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const dateBr = (value) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "—";
const labels = { pending: "Pendente", partial: "Parcial", paid: "Pago", overdue: "Vencido", cancelled: "Cancelado" };
const today = () => new Date().toISOString().slice(0, 10);

export default function PersonalFinance({ students = [] }) {
  const [charges, setCharges] = useState([]), [summary, setSummary] = useState(null), [state, setState] = useState("loading"), [error, setError] = useState("");
  const [filter, setFilter] = useState("all"), [studentId, setStudentId] = useState(""), [modal, setModal] = useState(null), [saving, setSaving] = useState(false);
  const load = async () => { setState("loading"); setError(""); try { const suffix = studentId ? `?student_id=${studentId}` : ""; const [rows, totals] = await Promise.all([apiRequest(`/finance/charges${suffix}`), apiRequest("/finance/summary")]); setCharges(rows); setSummary(totals); setState("success"); } catch (e) { setError(e.detail || e.message || "Não foi possível carregar o financeiro."); setState("error"); } };
  useEffect(() => { load(); }, [studentId]);
  const visible = useMemo(() => filter === "all" ? charges : charges.filter((charge) => charge.status === filter), [charges, filter]);
  const studentName = (id) => students.find((student) => student.id === id)?.name || "Aluno";
  const submitCharge = async (event) => { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await apiRequest("/finance/charges", { method: "POST", body: JSON.stringify({ student_id: data.get("student_id"), description: data.get("description"), amount: String(data.get("amount")).replace(",", "."), due_date: data.get("due_date"), notes: data.get("notes") || null }) }); setModal(null); await load(); } catch (e) { setError(e.detail || e.message || "Não foi possível criar a cobrança."); } finally { setSaving(false); } };
  const submitPayment = async (event, charge) => { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await apiRequest(`/finance/charges/${charge.id}/payments`, { method: "POST", body: JSON.stringify({ amount: String(data.get("amount")).replace(",", "."), paid_at: data.get("paid_at"), payment_method: data.get("payment_method") || null, notes: data.get("notes") || null }) }); setModal(null); await load(); } catch (e) { setError(e.detail || e.message || "Não foi possível registrar o pagamento."); } finally { setSaving(false); } };
  const cancel = async (charge) => { if (!window.confirm(`Cancelar a cobrança “${charge.description}”?`)) return; try { await apiRequest(`/finance/charges/${charge.id}/cancel`, { method: "POST" }); setModal(null); await load(); } catch (e) { setError(e.detail || e.message || "Não foi possível cancelar."); } };

  return <section className="finance-real-page"><header className="finance-real-header"><div><p className="eyebrow">Gestão financeira</p><h2>Financeiro</h2><span>Cobranças e recebimentos registrados pelo Personal.</span></div><button type="button" onClick={() => setModal({ type: "charge" })} disabled={!students.length}><Plus size={18} /> Nova cobrança</button></header>
    {summary && <div className="finance-summary-grid"><article><Wallet /><span>A receber</span><strong>{brl.format(summary.receivable)}</strong></article><article><CircleDollarSign /><span>Recebido no mês</span><strong>{brl.format(summary.received_month)}</strong></article><article><Ban /><span>Vencido</span><strong>{brl.format(summary.overdue)}</strong></article><article><Receipt /><span>Cobranças pendentes</span><strong>{summary.pending_count}</strong></article></div>}
    <div className="finance-filters"><label><span>Aluno</span><select value={studentId} onChange={(e) => setStudentId(e.target.value)}><option value="">Todos</option>{students.map((student) => <option value={student.id} key={student.id}>{student.name}</option>)}</select></label><div role="group" aria-label="Filtrar cobranças">{[["all","Todos"],["pending","Pendentes"],["partial","Parciais"],["overdue","Vencidos"],["paid","Pagos"],["cancelled","Cancelados"]].map(([key,label]) => <button type="button" className={filter === key ? "active" : ""} onClick={() => setFilter(key)} key={key}>{label}</button>)}</div></div>
    {state === "loading" && <div className="tenant-data-state">Carregando financeiro...</div>}{state === "error" && <div className="tenant-data-state"><strong>Falha ao carregar</strong><span>{error}</span><button type="button" onClick={load}>Tentar novamente</button></div>}
    {state === "success" && !charges.length && <div className="tenant-data-state"><Receipt size={28} /><strong>Nenhuma cobrança registrada.</strong><span>Crie uma cobrança para começar o histórico financeiro.</span></div>}
    {!!visible.length && <div className="finance-charge-cards">{visible.map((charge) => <article key={charge.id}><header><div><strong>{charge.description}</strong><span>{studentName(charge.student_id)}</span></div><mark data-status={charge.status}>{labels[charge.status]}</mark></header><dl><div><dt>Valor</dt><dd>{brl.format(charge.amount)}</dd></div><div><dt>Pago</dt><dd>{brl.format(charge.paid_amount)}</dd></div><div><dt>Saldo</dt><dd>{brl.format(charge.balance)}</dd></div><div><dt>Vencimento</dt><dd>{dateBr(charge.due_date)}</dd></div></dl><footer><button type="button" onClick={() => setModal({ type: "detail", charge })}>Ver histórico</button>{!["paid","cancelled"].includes(charge.status) && <button type="button" onClick={() => setModal({ type: "payment", charge })}>Registrar pagamento</button>}{!["paid","cancelled"].includes(charge.status) && Number(charge.paid_amount) === 0 && <button type="button" onClick={() => cancel(charge)}>Cancelar</button>}</footer></article>)}</div>}
    {error && state !== "error" && <p className="form-error" role="alert">{typeof error === "string" ? error : "Não foi possível concluir a ação."}</p>}
    {modal && <div className="finance-real-backdrop" onMouseDown={() => !saving && setModal(null)}><section className="finance-real-modal" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" type="button" aria-label="Fechar" onClick={() => setModal(null)}><X /></button>{modal.type === "charge" && <form onSubmit={submitCharge}><h3>Nova cobrança</h3><label><span>Aluno *</span><select name="student_id" required>{students.map((student) => <option value={student.id} key={student.id}>{student.name}</option>)}</select></label><label><span>Descrição *</span><input name="description" required /></label><label><span>Valor *</span><input name="amount" required inputMode="decimal" placeholder="199,90" /></label><label><span>Vencimento *</span><input name="due_date" type="date" required /></label><label><span>Observação</span><textarea name="notes" rows="3" /></label><button type="submit" disabled={saving}>{saving ? "Salvando..." : "Criar cobrança"}</button></form>}{modal.type === "payment" && <form onSubmit={(e) => submitPayment(e, modal.charge)}><h3>Registrar pagamento</h3><p>Saldo: <strong>{brl.format(modal.charge.balance)}</strong></p><label><span>Valor recebido *</span><input name="amount" required inputMode="decimal" defaultValue={String(modal.charge.balance).replace(".", ",")} /></label><label><span>Data *</span><input name="paid_at" type="date" required defaultValue={today()} /></label><label><span>Forma</span><select name="payment_method"><option value="">Não informada</option><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="card">Cartão</option><option value="transfer">Transferência</option><option value="other">Outro</option></select></label><label><span>Observação</span><textarea name="notes" rows="3" /></label><button type="submit" disabled={saving}>{saving ? "Salvando..." : "Confirmar recebimento"}</button></form>}{modal.type === "detail" && <div><h3>{modal.charge.description}</h3><p>{studentName(modal.charge.student_id)} · vencimento {dateBr(modal.charge.due_date)}</p><dl className="finance-detail-values"><div><dt>Valor</dt><dd>{brl.format(modal.charge.amount)}</dd></div><div><dt>Saldo</dt><dd>{brl.format(modal.charge.balance)}</dd></div></dl><h4>Histórico de pagamentos</h4>{modal.charge.payments.length ? <ul className="finance-payment-history">{modal.charge.payments.map((payment) => <li key={payment.id}><span>{dateBr(payment.paid_at)}</span><strong>{brl.format(payment.amount)}</strong><small>{payment.payment_method || "Não informado"}</small></li>)}</ul> : <p>Nenhum pagamento registrado.</p>}</div>}</section></div>}
  </section>;
}
