import React, { useEffect, useState } from "react";
import { Archive, ChevronDown, ChevronUp, Plus, Save, Trash2, Utensils, X } from "lucide-react";
import { apiRequest } from "../services/api.js";

const units = ["g", "kg", "ml", "L", "unidade", "colher", "xícara", "fatia", "porção"];
const blank = (student_id = "") => ({ student_id, name: "", start_date: new Date().toISOString().slice(0, 10), end_date: "", notes: "", meals: [] });
const meal = () => ({ name: "", time: "", notes: "", items: [] });
const item = () => ({ food_name: "", quantity: "", unit: "g", notes: "" });
const edit = (plan) => ({ ...plan, end_date: plan.end_date || "", meals: plan.meals.map((m) => ({ ...m, time: m.time?.slice(0, 5) || "", items: m.items.map((i) => ({ ...i, quantity: String(i.quantity) })) })) });
const move = (list, index, delta) => { const target = index + delta; if (target < 0 || target >= list.length) return list; const next = [...list]; [next[index], next[target]] = [next[target], next[index]]; return next; };

export default function PersonalDiet({ students = [] }) {
  const [studentId, setStudentId] = useState(students[0]?.id || "");
  const [plans, setPlans] = useState([]), [state, setState] = useState("loading"), [error, setError] = useState("");
  const [draft, setDraft] = useState(null), [saving, setSaving] = useState(false);
  useEffect(() => { if (!studentId && students[0]?.id) setStudentId(students[0].id); }, [studentId, students]);
  const load = async () => { if (!studentId) { setPlans([]); setState("success"); return; } setState("loading"); setError(""); try { setPlans(await apiRequest(`/meal-plans?student_id=${studentId}`)); setState("success"); } catch (e) { setError(e.detail || e.message || "Não foi possível carregar os planos."); setState("error"); } };
  useEffect(() => { load(); }, [studentId]);
  const setMeal = (mi, field, value) => setDraft((d) => ({ ...d, meals: d.meals.map((m, i) => i === mi ? { ...m, [field]: value } : m) }));
  const setItem = (mi, ii, field, value) => setDraft((d) => ({ ...d, meals: d.meals.map((m, i) => i !== mi ? m : { ...m, items: m.items.map((it, j) => j === ii ? { ...it, [field]: value } : it) }) }));
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); const payload = { ...draft, end_date: draft.end_date || null, meals: draft.meals.map((m) => ({ ...m, time: m.time || null, items: m.items.map((i) => ({ ...i, quantity: Number(String(i.quantity).replace(",", ".")) })) })) }; try { await apiRequest(draft.id ? `/meal-plans/${draft.id}` : "/meal-plans", { method: draft.id ? "PUT" : "POST", body: JSON.stringify(payload) }); setDraft(null); await load(); } catch (e) { setError(e.detail || e.message || "Não foi possível salvar o plano."); } finally { setSaving(false); } };
  const archive = async (plan) => { if (!window.confirm(`Arquivar “${plan.name}”?`)) return; await apiRequest(`/meal-plans/${plan.id}/archive`, { method: "POST" }); await load(); };

  return <section className="meal-plan-page"><header className="meal-plan-header"><div><p className="eyebrow">Plano Alimentar</p><h2>Dietas dos alunos</h2><span>Crie orientações estruturadas e preserve o histórico.</span></div><button type="button" onClick={() => setDraft(blank(studentId))} disabled={!studentId}><Plus size={18} /> Novo plano alimentar</button></header>
    <label className="meal-student-select"><span>Aluno</span><select value={studentId} onChange={(e) => setStudentId(e.target.value)}>{students.length ? students.map((s) => <option value={s.id} key={s.id}>{s.name}</option>) : <option value="">Nenhum aluno disponível</option>}</select></label>
    {state === "loading" && <div className="tenant-data-state">Carregando planos...</div>}{state === "error" && <div className="tenant-data-state"><strong>Falha ao carregar</strong><span>{error}</span><button type="button" onClick={load}>Tentar novamente</button></div>}
    {state === "success" && !plans.length && <div className="tenant-data-state"><Utensils size={28} /><strong>Nenhum plano alimentar cadastrado</strong><span>Crie o primeiro plano para este aluno.</span></div>}
    {!!plans.length && <div className="meal-history"><h3>Plano atual e histórico</h3>{plans.map((p) => <article key={p.id} className={p.status === "active" ? "active" : ""}><div><strong>{p.name}</strong><span>Início: {new Date(`${p.start_date}T12:00:00`).toLocaleDateString("pt-BR")}</span><small>{p.meals.length} refeições</small></div><mark>{p.status === "active" ? "Ativo" : "Arquivado"}</mark><button type="button" onClick={() => setDraft(edit(p))}>Visualizar e editar</button>{p.status === "active" && <button type="button" onClick={() => archive(p)}><Archive size={16} /> Arquivar</button>}</article>)}</div>}
    {error && state !== "error" && <p className="form-error" role="alert">{typeof error === "string" ? error : "Não foi possível concluir a ação."}</p>}
    {draft && <div className="meal-builder-backdrop" onMouseDown={() => !saving && setDraft(null)}><form className="meal-builder" role="dialog" aria-modal="true" onSubmit={save} onMouseDown={(e) => e.stopPropagation()}><header><div><p className="eyebrow">{draft.id ? "Editar plano" : "Novo plano"}</p><h2>Plano Alimentar</h2></div><button type="button" aria-label="Fechar" onClick={() => setDraft(null)}><X /></button></header>
      <div className="meal-plan-fields"><label><span>Aluno *</span><select value={draft.student_id} disabled={!!draft.id} onChange={(e) => setDraft({ ...draft, student_id: e.target.value })}>{students.map((s) => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label><span>Nome *</span><input required value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label><span>Início *</span><input required type="date" value={draft.start_date} onChange={(e) => setDraft({ ...draft, start_date: e.target.value })} /></label><label><span>Final</span><input type="date" value={draft.end_date} onChange={(e) => setDraft({ ...draft, end_date: e.target.value })} /></label><label className="wide"><span>Observações</span><textarea rows="3" value={draft.notes || ""} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} /></label></div>
      <div className="meal-builder-title"><h3>Refeições</h3><button type="button" onClick={() => setDraft({ ...draft, meals: [...draft.meals, meal()] })}><Plus size={17} /> Adicionar refeição</button></div>
      {draft.meals.map((m, mi) => <fieldset className="meal-editor" key={m.id || mi}><legend>Refeição {mi + 1}</legend><div className="meal-editor-actions"><button type="button" aria-label="Mover refeição para cima" onClick={() => setDraft({ ...draft, meals: move(draft.meals, mi, -1) })}><ChevronUp /></button><button type="button" aria-label="Mover refeição para baixo" onClick={() => setDraft({ ...draft, meals: move(draft.meals, mi, 1) })}><ChevronDown /></button><button type="button" aria-label="Remover refeição" onClick={() => setDraft({ ...draft, meals: draft.meals.filter((_, i) => i !== mi) })}><Trash2 /></button></div><div className="meal-plan-fields"><label><span>Nome *</span><input required value={m.name} onChange={(e) => setMeal(mi, "name", e.target.value)} /></label><label><span>Horário</span><input type="time" value={m.time} onChange={(e) => setMeal(mi, "time", e.target.value)} /></label><label className="wide"><span>Observações</span><input value={m.notes || ""} onChange={(e) => setMeal(mi, "notes", e.target.value)} /></label></div>
      <div className="meal-items">{m.items.map((it, ii) => <div className="meal-item-editor" key={it.id || ii}><label><span>Alimento *</span><input required value={it.food_name} onChange={(e) => setItem(mi, ii, "food_name", e.target.value)} /></label><label><span>Quantidade *</span><input required inputMode="decimal" value={it.quantity} onChange={(e) => setItem(mi, ii, "quantity", e.target.value)} /></label><label><span>Unidade *</span><select value={it.unit} onChange={(e) => setItem(mi, ii, "unit", e.target.value)}>{units.map((u) => <option key={u}>{u}</option>)}</select></label><label><span>Orientação</span><input value={it.notes || ""} onChange={(e) => setItem(mi, ii, "notes", e.target.value)} /></label><div><button type="button" aria-label="Mover alimento para cima" onClick={() => setMeal(mi, "items", move(m.items, ii, -1))}><ChevronUp /></button><button type="button" aria-label="Mover alimento para baixo" onClick={() => setMeal(mi, "items", move(m.items, ii, 1))}><ChevronDown /></button><button type="button" aria-label="Remover alimento" onClick={() => setMeal(mi, "items", m.items.filter((_, i) => i !== ii))}><Trash2 /></button></div></div>)}<button type="button" className="add-food" onClick={() => setMeal(mi, "items", [...m.items, item()])}><Plus size={16} /> Adicionar alimento</button></div></fieldset>)}
      <footer><button type="button" onClick={() => setDraft(null)}>Cancelar</button><button type="submit" disabled={saving}><Save size={18} /> {saving ? "Salvando..." : "Salvar plano"}</button></footer></form></div>}
  </section>;
}
