import React, { useEffect, useState } from "react";
import { Eye, EyeOff } from "lucide-react";
import { apiRequest } from "../services/api.js";

export default function StudentFirstAccess({ slug, branding }) {
  const token = new URLSearchParams(window.location.search).get("token") || "";
  const [status, setStatus] = useState("loading");
  const [error, setError] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [loginPath, setLoginPath] = useState("");
  useEffect(() => { let active = true; apiRequest(`/auth/student-invites/validate?token=${encodeURIComponent(token)}&slug=${encodeURIComponent(slug)}`, { skipAuthRefresh: true }).then(() => active && setStatus("ready")).catch((requestError) => { if (active) { setStatus("invalid"); setError(requestError.message); } }); return () => { active = false; }; }, [slug, token]);
  const submit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get("new_password") !== form.get("confirm_password")) return setError("As senhas não coincidem."); setStatus("saving"); setError(""); try { const result = await apiRequest("/auth/student-invites/activate", { method: "POST", skipAuthRefresh: true, body: JSON.stringify({ token, slug, first_name: form.get("first_name"), last_name: form.get("last_name"), new_password: form.get("new_password"), confirm_password: form.get("confirm_password") }) }); setLoginPath(result.login_path); setStatus("success"); window.history.replaceState(null, "", window.location.pathname); } catch (requestError) { setStatus("ready"); setError(requestError.message); } };
  return <main className="student-first-access"><section><header>{branding?.logo_url && <img src={branding.logo_url} alt={branding.display_name || "Personal"}/>}<p className="eyebrow">{branding?.display_name || "Seu Personal"}</p><h1>{status === "success" ? "Seu acesso está pronto!" : "Bem-vindo(a) à plataforma"}</h1></header>{status === "loading" && <p role="status">Validando seu convite...</p>}{status === "invalid" && <div role="alert"><p>{error || "Este convite já foi utilizado ou não é mais válido."}</p><small>Peça ao seu Personal um novo convite de acesso.</small></div>}{status === "success" && <><p>Sua senha foi criada com segurança. Entre com seu e-mail para continuar.</p><a className="metal-button" href={loginPath}>Entrar na plataforma</a></>}{["ready", "saving"].includes(status) && <form onSubmit={submit}><fieldset><legend>Confirme seus dados</legend><label>Nome<input name="first_name" required autoComplete="given-name"/></label><label>Sobrenome<input name="last_name" autoComplete="family-name"/></label></fieldset><fieldset><legend>Crie sua senha</legend><p>Use pelo menos 10 caracteres.</p><label>Nova senha<span className="password-field"><input name="new_password" type={showPassword ? "text" : "password"} minLength="10" maxLength="128" required autoComplete="new-password"/><button type="button" aria-label={showPassword ? "Ocultar senha" : "Mostrar senha"} onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff/> : <Eye/>}</button></span></label><label>Confirmar senha<input name="confirm_password" type={showPassword ? "text" : "password"} minLength="10" maxLength="128" required autoComplete="new-password"/></label></fieldset>{error && <p className="form-error" role="alert">{error}</p>}<button className="metal-button" type="submit" disabled={status === "saving"}>{status === "saving" ? "Ativando acesso..." : "Criar meu acesso"}</button></form>}</section></main>;
}
